server: 
  port: 9002
spring:  application:    name: nacos-payment-provider
  cloud:    nacos:      discovery:
        server-addr: 192.168.1.100:1111
management:  endpoints:    web:      exposure:        include: "*"
