server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false  #不注册自己
    register-with-eureka: false # 不检 索自己
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka  #集群配置  server:    enable-self-preservation: false #禁用禁用自我保护模式
    eviction-interval-timer-in-ms: 2000
